# Site settings
title: jsunny9860
description: jsunny9860 is blog test.
cover: assets/images/radhakrishna.jpg
logo: assets/images/logo.png
favicon: assets/images/favicon.png
baseurl: "/hanuman/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://jsunny9860.github.io/" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

# Social
facebook: facebook
twitter: twitter
github:  github

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: jsunny9860 #github username
repo: hanuman #github repository
branch: master #branch
relative_source: ../jsunny9860.github.io/ #source directory
destination: ../jsunny9860.github.io/ #destination directory
production_url:  https://jsunny9860.github.io
source_url:  https://github.com/jsunny9860/jsunny9860.github.io #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml